using Godot;

namespace TheAugur.TheAugurCode.Extensions;

//Mostly utilities to get asset paths. Mirrors TheWitchCode/Extensions/StringExtensions.cs (minus the beta-images config).
public static class StringExtensions
{
    /// <summary>res:// paths must use '/' separators; Path.Join emits backslashes on Windows, which the
    /// game's string-keyed asset cache treats as a different path.</summary>
    private static string ResJoin(params string[] parts) => string.Join('/', parts);

    /// <summary>Join under images/<paramref name="relDir"/>; fall back to the category placeholder (with a log) when missing.</summary>
    private static string Resolve(string relDir, string path, string placeholder)
    {
        string full = ResJoin(MainFile.ResPath, "images", relDir, path);
        if (ResourceLoader.Exists(full)) return full;

        MainFile.Logger.Info($"Could not find image path: {full}");
        return ResJoin(MainFile.ResPath, "images", relDir, placeholder);
    }

    public static string ImagePath(this string path)
    {
        return ResJoin(MainFile.ResPath, "images", path);
    }

    /// <summary>An AtlasTexture slice generated by tools/pack-atlases.py from the card_portraits/ source art.</summary>
    public static string CardAtlasPath(this string path)
    {
        string sprites = ResJoin(MainFile.ResPath, "images", "atlases", "card_atlas.sprites");
        string full = ResJoin(sprites, path);
        if (ResourceLoader.Exists(full)) return full;

        MainFile.Logger.Info($"Could not find card atlas slice: {full}");
        return ResJoin(sprites, "card.tres");
    }

    private static string ResolveAtlas(string spritesDir, string path, string placeholder)
    {
        string full = ResJoin(MainFile.ResPath, "images", "atlases", spritesDir, path);
        if (ResourceLoader.Exists(full)) return full;

        MainFile.Logger.Info($"Could not find atlas slice: {full}");
        return ResJoin(MainFile.ResPath, "images", "atlases", spritesDir, placeholder);
    }

    public static string RelicAtlasPath(this string path) => ResolveAtlas("relic_atlas.sprites", path, "relic.tres");
    public static string PowerAtlasPath(this string path) => ResolveAtlas("power_atlas.sprites", path, "power.tres");
    public static string PotionAtlasPath(this string path) => ResolveAtlas("potion_atlas.sprites", path, "potion.tres");
    public static string RelicOutlineAtlasPath(this string path) => ResolveAtlas("relic_atlas.sprites", path, "relic_outline.tres");
    public static string PotionOutlineAtlasPath(this string path) => ResJoin(MainFile.ResPath, "images", "atlases", "potion_atlas.sprites", path);

    public static string BigPowerImagePath(this string path) => Resolve("powers", path, "power.png");
    public static string BigRelicImagePath(this string path) => Resolve("relics", path, "relic.png");

    public static string CharacterUiPath(this string path) => ResJoin(MainFile.ResPath, "images", "charui", path);
    public static string CharacterSfxPath(this string path) => ResJoin(MainFile.ResPath, "sfx", path);
    public static string CharacterScenePath(this string path) => ResJoin(MainFile.ResPath, "scenes", path);
    public static string VfxScenePath(this string path) => ResJoin(MainFile.ResPath, "scenes", "vfx", path);
    public static string ShaderPath(this string path) => ResJoin(MainFile.ResPath, "Shaders", path);
}
