#!/usr/bin/env py
"""Generate missing big/small charui variants + seed placeholder art.

Only charui still ships paired sizes (small + ``big/``, e.g. map marker,
char-select art, energy icons); this script downscales big/ art to the
existing small's exact dimensions (downscale-only, never upscales):

    TheWitch/images/charui/foo.png                      (small)
    TheWitch/images/charui/big/foo.png                  (big)

Cards, relics, powers, potions, and pets ship as atlas slices generated by
tools/pack-atlases.py (which also generates the relic/potion outline slices) —
no small variants exist for those anymore. Their single-size source art:
cards ``card_portraits/`` (.gdignore'd), relics ``relics/`` + powers
``powers/`` (256, also shipped loose for the BigIcon views), potions
``potions/`` (256, .gdignore'd), pets ``pets/`` (512, .gdignore'd).

The seeding passes fill in placeholder art for brand-new powers and potions
from their localization title keys — the authoritative content lists —
(``power.png`` / ``potion.png`` copied to the entry's source path). Cards need
no seeding: a card with no art falls back to the packed ``card.tres``
placeholder slice at runtime.

Usage:
    py tools/gen-image-sizes.py big/big_energy.png  # scale ONE big -> small
    py tools/gen-image-sizes.py                 # bulk: seeding + charui pass
    py tools/gen-image-sizes.py --dry-run       # show what would happen
    py tools/gen-image-sizes.py --category powers   # seed-only category
    py tools/gen-image-sizes.py --nearest       # nearest-neighbour (pixel art)

Single-image mode (a big-image path argument) downscales just that one file to
its small counterpart — the same path with the 'big/' folder removed, reusing
the existing small's exact dimensions (falls back to 1/scale when new).
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required. Install it with:  py -m pip install Pillow")

# Repo root is the parent of this tools/ folder.
REPO_ROOT = Path(__file__).resolve().parent.parent
IMAGES_ROOT = REPO_ROOT / "TheWitch" / "images"

# Category -> (small_dir, big_dir). Optional keys:
#   no_upscale — downscale-only: never generate big/ from small
#   derived    — {dst: src} files generated by downscaling ANOTHER small in the
#                same dir (text_energy from big_energy); excluded from pairing
CATEGORIES = {
    "charui": {"small": IMAGES_ROOT / "charui",
               "big": IMAGES_ROOT / "charui" / "big",
               "no_upscale": True,
               "derived": {"text_energy.png": "big_energy.png"}},
}

# Localization files are the authoritative content lists for powers/potions
# (every shipped power/potion must have a .title loc entry). Used for seeding.
LOC_DIR = REPO_ROOT / "TheWitch" / "localization" / "eng"
POWER_PLACEHOLDER = IMAGES_ROOT / "powers" / "power.png"
POWERS_DIR = IMAGES_ROOT / "powers"
POTION_PLACEHOLDER = IMAGES_ROOT / "potions" / "potion.png"
POTIONS_DIR = IMAGES_ROOT / "potions"


def loc_entries(loc_name: str) -> list[str]:
    """Lowercased id entries from a localization file's THEWITCH-*.title keys."""
    loc_file = LOC_DIR / loc_name
    if not loc_file.exists():
        print(f"[seed] loc file not found: {loc_file} (skipped)")
        return []
    keys = json.loads(loc_file.read_text(encoding="utf-8-sig"))
    return [k[len("THEWITCH-"):-len(".title")].lower()
            for k in keys if k.endswith(".title")]


def seed_loc_placeholders(loc_name: str, target_dir: Path, placeholder: Path,
                          label: str, dry_run: bool) -> int:
    """Copy the category placeholder for any loc-listed entry with no art yet.
    Never clobbers existing art."""
    if not placeholder.exists():
        print(f"[seed:{label}] placeholder not found: {placeholder} (skipped)")
        return 0
    seeded = 0
    for entry in loc_entries(loc_name):
        dst = target_dir / f"{entry}.png"
        if dst.exists():
            continue
        print(f"  seed      placeholder -> {dst.relative_to(REPO_ROOT)}")
        if not dry_run:
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(placeholder, dst)
        seeded += 1
    print(f"[seed:{label}] {seeded} placeholder(s){' (dry run)' if dry_run else ''}")
    return seeded


def resize(src: Path, dst: Path, factor: float, resample, dry_run: bool) -> None:
    with Image.open(src) as img:
        target = (max(1, round(img.size[0] * factor)), max(1, round(img.size[1] * factor)))
        verb = "upscale" if factor > 1 else "downscale"
        print(f"  {verb:9} {img.size[0]}x{img.size[1]} -> {target[0]}x{target[1]}"
              f"  {src.relative_to(REPO_ROOT)}  ->  {dst.relative_to(REPO_ROOT)}")
        if dry_run:
            return
        out = img.resize(target, resample)
        dst.parent.mkdir(parents=True, exist_ok=True)
        out.save(dst)


def resize_exact(src: Path, dst: Path, target: tuple[int, int], resample,
                 dry_run: bool) -> None:
    """Resize src to an explicit target (w, h)."""
    with Image.open(src) as img:
        verb = "upscale" if target[0] > img.size[0] else "downscale"
        print(f"  {verb:9} {img.size[0]}x{img.size[1]} -> {target[0]}x{target[1]}"
              f"  {src.relative_to(REPO_ROOT)}  ->  {dst.relative_to(REPO_ROOT)}")
        if dry_run:
            return
        out = img.resize(target, resample)
        dst.parent.mkdir(parents=True, exist_ok=True)
        out.save(dst)


def small_path_for_big(big_path: Path) -> Path:
    """The small counterpart of a big image: the same path with the 'big/'
    folder segment removed (charui/big/x.png -> charui/x.png)."""
    parts = list(big_path.parts)
    if "big" not in parts:
        sys.exit(f"Not a 'big' image (no 'big/' folder in path): {big_path}")
    parts.remove("big")  # the first 'big' segment is the size mirror
    return Path(*parts)


def resolve_big(arg: str) -> Path:
    """Resolve a user-supplied big-image argument to an actual file. Accepts an
    absolute path, a repo-relative path, an images-root-relative path (e.g.
    'charui/big/foo.png'), or just 'big/foo.png' / 'foo.png' — in which case we
    glob for a unique match under any 'big/' folder."""
    for cand in (Path(arg), REPO_ROOT / arg, IMAGES_ROOT / arg):
        if cand.is_file():
            return cand.resolve()
    base = Path(arg).name
    matches = sorted({p.resolve() for p in IMAGES_ROOT.glob(f"**/big/**/{base}")
                      if "beta" not in p.parts})
    if len(matches) == 1:
        return matches[0]
    if len(matches) > 1:
        rels = ", ".join(str(m.relative_to(REPO_ROOT)) for m in matches)
        sys.exit(f"Ambiguous big image '{arg}' — matches: {rels}. Pass a fuller path.")
    sys.exit(f"Big image not found: {arg}")


def scale_one_big(arg: str, scale: float, resample, dry_run: bool) -> int:
    """Downscale a single big image to its small counterpart. Target size:
    the existing small's exact dimensions, else fall back to 1/scale."""
    big_path = resolve_big(arg)
    small_path = small_path_for_big(big_path)
    if small_path.exists():
        with Image.open(small_path) as s:
            resize_exact(big_path, small_path, s.size, resample, dry_run)
    else:
        resize(big_path, small_path, 1 / scale, resample, dry_run)
    return 1


def process_category(name: str, cfg: dict, scale: float,
                     resample, force: bool, dry_run: bool) -> int:
    small_dir, big_dir = cfg["small"], cfg["big"]
    if not small_dir.exists():
        print(f"[{name}] small dir not found: {small_dir} (skipped)")
        return 0

    # Names present on either side (small dir is non-recursive so the big/
    # subfolder is not double-counted).
    small_names = {p.name for p in small_dir.glob("*.png")}
    big_names = {p.name for p in big_dir.glob("*.png")} if big_dir.exists() else set()
    excluded = set(cfg.get("derived", {}).keys())

    print(f"[{name}] small={len(small_names)} big={len(big_names)}"
          + (f" excluded={len(excluded)}" if excluded else ""))
    generated = 0

    def make_small(big_path: Path, small_path: Path) -> None:
        # The existing small's exact dims win; else 1/scale.
        if small_path.exists():
            with Image.open(small_path) as s:
                resize_exact(big_path, small_path, s.size, resample, dry_run)
        else:
            resize(big_path, small_path, 1 / scale, resample, dry_run)

    for fname in sorted((small_names | big_names) - excluded):
        small_path = small_dir / fname
        big_path = big_dir / fname
        has_small = fname in small_names
        has_big = fname in big_names

        if has_small and not has_big:                       # make big from small
            if cfg.get("no_upscale"):
                continue
            resize(small_path, big_path, scale, resample, dry_run)
            generated += 1
        elif has_big and not has_small:                     # make small from big
            make_small(big_path, small_path)
            generated += 1
        elif has_small and has_big and force:               # regenerate small from big
            make_small(big_path, small_path)
            generated += 1

    # Derived files: downscaled from another small in the same dir. Regenerated
    # only with --force (the target's existing dims are the spec).
    for dst_name, src_name in cfg.get("derived", {}).items():
        src, dst = small_dir / src_name, small_dir / dst_name
        if not src.exists():
            print(f"  derived source missing: {src.relative_to(REPO_ROOT)} (skipped)")
            continue
        if not dst.exists():
            print(f"  derived target missing, size unknown: "
                  f"{dst.relative_to(REPO_ROOT)} (skipped)")
            continue
        if not force:
            continue
        with Image.open(dst) as d:
            target = d.size
        resize_exact(src, dst, target, resample, dry_run)
        generated += 1

    if generated == 0:
        print("  nothing to do")
    return generated


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("big_image", nargs="?",
                        help="Scale a single big image down to its small variant "
                             "and exit (e.g. 'big/big_energy.png'). Without this, "
                             "runs seeding + the charui pass.")
    parser.add_argument("--category", choices=sorted(CATEGORIES) + ["powers", "potions"],
                        help="Only process this category (default: all). "
                             "'powers' and 'potions' are seed-only.")
    parser.add_argument("--scale", type=float, default=4.0,
                        help="big = small * scale (default: 4).")
    parser.add_argument("--force", action="store_true",
                        help="Regenerate small from big even when both exist "
                             "(big art is the source of truth); also refreshes "
                             "derived files like text_energy.")
    parser.add_argument("--nearest", action="store_true",
                        help="Nearest-neighbour resampling (crisp pixel art) "
                             "instead of Lanczos.")
    parser.add_argument("--no-seed", action="store_true",
                        help="Skip seeding placeholders for powers/potions "
                             "that have no art yet.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print actions without writing files.")
    args = parser.parse_args()

    if args.scale <= 0:
        sys.exit("--scale must be > 0")

    resample = Image.NEAREST if args.nearest else Image.LANCZOS

    # Single-image mode: scale just the one big image down to its small variant.
    if args.big_image:
        total = scale_one_big(args.big_image, args.scale, resample, args.dry_run)
        print()
        print(f"{'Dry run: ' if args.dry_run else ''}{total} variant(s)"
              f"{' would be' if args.dry_run else ''} generated.")
        return 0

    cats = ({args.category: CATEGORIES[args.category]} if args.category in CATEGORIES
            else {} if args.category else CATEGORIES)

    if not args.no_seed:
        if args.category in (None, "powers"):
            seed_loc_placeholders("powers.json", POWERS_DIR,
                                  POWER_PLACEHOLDER, "powers", args.dry_run)
            print()
        if args.category in (None, "potions"):
            seed_loc_placeholders("potions.json", POTIONS_DIR,
                                  POTION_PLACEHOLDER, "potions", args.dry_run)
            print()

    total = 0
    for name, cfg in cats.items():
        total += process_category(name, cfg, args.scale, resample,
                                  args.force, args.dry_run)

    print()
    if args.dry_run:
        print(f"Dry run: {total} variant(s) would be generated.")
    else:
        print(f"Generated {total} variant(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
