using Godot;
using TheWitch.TheWitchCode.Config;

namespace TheWitch.TheWitchCode.Extensions;

//Mostly utilities to get asset paths.
public static class StringExtensions
{
    /// <summary>res:// paths must use '/' separators; Path.Join emits '\' on Windows, which the
    /// game's string-keyed asset cache treats as a different path.</summary>
    private static string ResJoin(params string[] parts) => string.Join('/', parts);

    /// <summary>Join under images/<paramref name="relDir"/>; fall back to the category placeholder (with a log) when missing.</summary>
    private static string Resolve(string relDir, string path, string placeholder)
    {
        string full = ResJoin(MainFile.ResPath, "images", relDir, path);
        if (ResourceLoader.Exists(full)) return full;

        MainFile.Logger.Info($"Could not find image path: {full}");
        return ResJoin(MainFile.ResPath, "images", relDir, placeholder);
    }

    public static string ImagePath(this string path)
    {
        return ResJoin(MainFile.ResPath, "images", path);
    }

    /// <summary>An AtlasTexture slice generated by tools/pack-atlases.py from the card_portraits/ source art.
    /// <paramref name="path"/> is the slice inside card_atlas.sprites/ (e.g. "ambush.tres", "familiar/gnash.tres");
    /// the beta/ variant wins when the Beta Images config is on and the slice exists.</summary>
    public static string CardAtlasPath(this string path)
    {
        string sprites = ResJoin(MainFile.ResPath, "images", "atlases", "card_atlas.sprites");
        if (WitchConfig.BetaImages)
        {
            string beta = ResJoin(sprites, "beta", path);
            if (ResourceLoader.Exists(beta)) return beta;
        }

        string full = ResJoin(sprites, path);
        if (ResourceLoader.Exists(full)) return full;

        MainFile.Logger.Info($"Could not find card atlas slice: {full}");
        return ResJoin(sprites, "card.tres");
    }

    /// <summary>An AtlasTexture slice inside <paramref name="spritesDir"/> (e.g. "relic_atlas.sprites"),
    /// falling back to the packed placeholder slice (with a log) when missing.</summary>
    private static string ResolveAtlas(string spritesDir, string path, string placeholder)
    {
        string full = ResJoin(MainFile.ResPath, "images", "atlases", spritesDir, path);
        if (ResourceLoader.Exists(full)) return full;

        MainFile.Logger.Info($"Could not find atlas slice: {full}");
        return ResJoin(MainFile.ResPath, "images", "atlases", spritesDir, placeholder);
    }

    public static string RelicAtlasPath(this string path) => ResolveAtlas("relic_atlas.sprites", path, "relic.tres");
    public static string PowerAtlasPath(this string path) => ResolveAtlas("power_atlas.sprites", path, "power.tres");
    public static string PotionAtlasPath(this string path) => ResolveAtlas("potion_atlas.sprites", path, "potion.tres");

    /// <summary>Relic outline slice (white silhouette drawn behind the small icon); falls back to the
    /// placeholder's outline, not the colored relic art.</summary>
    public static string RelicOutlineAtlasPath(this string path) => ResolveAtlas("relic_atlas.sprites", path, "relic_outline.tres");

    /// <summary>Potion outline slice; no placeholder — the game treats a missing outline as "no outline"
    /// rather than drawing a wrong one.</summary>
    public static string PotionOutlineAtlasPath(this string path) => ResJoin(MainFile.ResPath, "images", "atlases", "potion_atlas.sprites", path);

    public static string BigPowerImagePath(this string path) => Resolve("powers", path, "power.png");
    public static string BigRelicImagePath(this string path) => Resolve("relics", path, "relic.png");

    public static string CharacterUiPath(this string path) => ResJoin(MainFile.ResPath, "images", "charui", path);
    public static string CharacterSfxPath(this string path) => ResJoin(MainFile.ResPath, "sfx", path);
    public static string CharacterScenePath(this string path) => ResJoin(MainFile.ResPath, "scenes", path);
    public static string VfxScenePath(this string path) => ResJoin(MainFile.ResPath, "scenes", "vfx", path);
    public static string ShaderPath(this string path) => ResJoin(MainFile.ResPath, "Shaders", path);
    public static string PetConfigPath(this string path) => ResJoin(MainFile.ResPath, "data", "pets", path);
}
